# English key -> French. Used to generate Resources/fr.lproj/Localizable.strings
FR = {
"Normal": "Normal",
"Background": "Arrière-plan",
"Hidden": "Caché",
"Opens and comes to the front.": "S'ouvre et passe au premier plan.",
"Opens behind your current window, without stealing focus.": "S'ouvre derrière ta fenêtre actuelle, sans te couper.",
"My apps": "Mes apps",
"New group": "Nouveau groupe",
"Accessibility": "Accessibilité",
"Screen Recording": "Enregistrement de l'écran",
"Input Monitoring": "Surveillance de l'entrée",
"Full Disk Access": "Accès complet au disque",
"Automation": "Automatisation",
"Icon": "Icône",
"Color": "Couleur",
"Settings": "Réglages",
"Quit all": "Tout quitter",
"Nothing to open": "Rien à ouvrir",
"Opening %lld apps…": "Ouverture de %lld apps…",
"Everything is already open": "Tout est déjà ouvert",
"%lld opened": "Ouvertes : %lld",
"%lld already open": "Déjà ouvertes : %lld",
"%lld not found": "Introuvables : %lld",
"Groups": "Groupes",
"Delete this group?": "Supprimer ce groupe ?",
"Delete": "Supprimer",
"Cancel": "Annuler",
"Your apps stay installed. Only the group is removed from Stack, and apps kept inside Stack go back to Applications.": "Tes apps restent installées. Seul le groupe est retiré de Stack, et les apps rangées dans Stack retournent dans Applications.",
"Quits every app of all your groups": "Quitte toutes les apps de tous tes groupes",
"Open group": "Ouvrir le groupe",
"Quit group": "Quitter le groupe",
"Don't open on click": "Ne pas ouvrir au clic",
"Open on click": "Ouvrir au clic",
"Delete group…": "Supprimer le groupe…",
"Opens when you click Stack": "S'ouvre quand tu cliques sur Stack",
"No group selected": "Aucun groupe sélectionné",
"Create a group": "Créer un groupe",
"Change icon and color": "Changer l'icône et la couleur",
"Group name": "Nom du groupe",
"When on, this group opens every time you click Stack.": "Activé : ce groupe s'ouvre à chaque clic sur Stack.",
"Open": "Ouvrir",
"Open every app of this group now": "Ouvrir maintenant toutes les apps du groupe",
"Quit": "Quitter",
"Quit every app of this group": "Quitter toutes les apps du groupe",
"Empty group": "Groupe vide",
"1 app": "1 app",
"%lld apps": "%lld apps",
"%lld running": "%lld en cours",
"No apps yet": "Aucune app pour l'instant",
"Drag apps here from the Finder, or pick them from the apps installed on your Mac.": "Glisse des apps ici depuis le Finder, ou choisis-les parmi les apps installées sur ton Mac.",
"Add apps": "Ajouter des apps",
"Add apps…": "Ajouter des apps…",
"Browse…": "Parcourir…",
"Tip: drag apps from the Finder into this window.": "Astuce : glisse des apps depuis le Finder dans cette fenêtre.",
"Drop to add": "Dépose pour ajouter",
"Add": "Ajouter",
"Locate…": "Localiser…",
"Not found (moved or uninstalled)": "Introuvable (déplacée ou désinstallée)",
"Running": "Ouverte",
"Not running": "Fermée",
"More": "Plus",
"Open now": "Ouvrir maintenant",
"Show in Finder": "Afficher dans le Finder",
"Permissions": "Autorisations",
"Remove from group": "Retirer du groupe",
"Choose": "Choisir",
"Where is %@?": "Où se trouve %@ ?",
"Add apps to “%@”": "Ajouter des apps à « %@ »",
"Search": "Rechercher",
"No app found": "Aucune app trouvée",
"Show system apps": "Apps système",
"Add %lld": "Ajouter %lld",
"Already added": "Déjà ajoutée",
"Show the bubble after opening": "Afficher la bulle après l'ouverture",
"A small panel with Settings and Quit all, for a few seconds.": "Un petit panneau avec Réglages et Tout quitter, pendant quelques secondes.",
"⌥ + click": "⌥ + clic",
"Open these settings": "Ouvrir ces réglages",
"Hold the Option key (⌥) while opening Stack.": "Maintiens la touche Option (⌥) en ouvrant Stack.",
"When you click Stack": "Quand tu cliques sur Stack",
"Open Stack at login": "Ouvrir Stack au démarrage du Mac",
"Your “open on click” groups open automatically when you log in.": "Tes groupes « Ouvrir au clic » s'ouvrent tout seuls à la connexion.",
"Needs your approval in System Settings": "À valider dans les Réglages Système",
"Open Login Items": "Ouvrir les Réglages",
"Startup": "Démarrage",
"macOS gives each permission to one app at a time: no app can pass its access on to the others. These shortcuts take you straight to the right place when an app asks again.": "macOS donne chaque autorisation à une seule app : aucune app ne peut transmettre ses accès aux autres. Ces raccourcis t'emmènent directement au bon endroit quand une app redemande l'accès.",
"Version": "Version",
"Stack itself": "Stack lui-même",
"Needs no special permission": "N'a besoin d'aucune autorisation",
"Show the settings file in the Finder": "Afficher le fichier de réglages dans le Finder",
"About": "À propos",
"About Stack": "À propos de Stack",
"Settings…": "Réglages…",
"Open my groups": "Ouvrir mes groupes",
"Quit all apps": "Quitter toutes les apps",
"Hide Stack": "Masquer Stack",
"Quit Stack": "Quitter Stack",
"Edit": "Édition",
"Undo": "Annuler",
"Redo": "Rétablir",
"Cut": "Couper",
"Copy": "Copier",
"Paste": "Coller",
"Select All": "Tout sélectionner",
"Window": "Fenêtre",
"Close": "Fermer",
"Minimize": "Réduire",
}
FR.update({
"Always hidden": "Toujours caché",
"Turn on “Open Stack at login” so hidden apps stay hidden after a restart.": "Active « Ouvrir Stack au démarrage du Mac » pour que ça marche aussi après un redémarrage.",
"Turn on": "Activer",
})

FR.update({
"Hidden apps": "Apps cachées",
})

FR.update({
"Opens with its windows hidden. Ideal for apps that just need to run, like Spotify.": "S'ouvre avec ses fenêtres masquées. Idéal pour les apps qui doivent juste tourner, comme Spotify.",
"Like Hidden, and stays hidden even when another app opens it (e.g. Sapphire opening Spotify). Stack keeps an icon in the menu bar for this.": "Comme Caché, et reste caché même quand une autre app l'ouvre (ex. Sapphire qui ouvre Spotify). Stack garde une icône dans la barre des menus pour ça.",
"Stack stays in the menu bar to look after %@.": "Stack reste dans la barre des menus pour gérer %@.",
"The app could not be found.": "L'app est introuvable.",
"macOS blocked the change. Allow Stack in System Settings › Privacy & Security › App Management, then try again.": "macOS a bloqué la modification. Autorise Stack dans Réglages Système › Confidentialité et sécurité › Gestion des apps, puis réessaie.",
"This app belongs to an administrator account, so Stack can't change it.": "Cette app appartient à un compte administrateur : Stack ne peut pas la modifier.",
"The app didn't quit. Quit it, then try again.": "L'app ne s'est pas fermée. Quitte-la, puis réessaie.",
"The app couldn't be re-signed, so nothing was changed.": "Impossible de re-signer l'app : rien n'a été modifié.",
"No backup found. Reinstall the app to get its Dock icon back.": "Aucune sauvegarde trouvée. Réinstalle l'app pour récupérer son icône dans le Dock.",
"Remove %@ from the Dock?": "Retirer %@ du Dock ?",
"Remove from Dock": "Retirer du Dock",
"Couldn't change %@": "Impossible de modifier %@",
"Open Settings": "Ouvrir les Réglages",
"OK": "OK",
"App Management": "Gestion des apps",
"Out of Dock": "Hors du Dock",
})
FR.update({
"This app uses protected Apple features (iCloud, keychain…) or is a system app, so it can't be changed safely.": "Cette app utilise des fonctions Apple protégées (iCloud, trousseau…) ou c'est une app système : impossible de la modifier sans risque.",
"Some apps couldn't be changed": "Certaines apps n'ont pas pu être modifiées",
"Remove %lld apps from the Dock?": "Retirer %lld apps du Dock ?",
"Stack changes one setting inside each app so it behaves like a menu bar app: no Dock icon, reachable from the menu bar. Running apps quit and reopen. An app may ask you to log in again, and Stack redoes this automatically after each update. You can put everything back at any time.": "Stack modifie un réglage dans chaque app pour qu'elle se comporte comme une app de la barre des menus : pas d'icône dans le Dock, accessible en haut. Les apps ouvertes se ferment puis se rouvrent. Une app peut te redemander de te connecter, et Stack refait la modification tout seul après chaque mise à jour. Tu peux tout remettre à tout moment.",
"Put all back": "Tout remettre",
"Remove all from Dock": "Tout retirer du Dock",
"Keep my apps out of the Dock": "Garder mes apps hors du Dock",
"%lld of %lld apps are out of the Dock. You reach them from Stack's menu bar icon (works with Ice).": "%lld sur %lld apps sont hors du Dock. Tu y accèdes par l'icône Stack en haut (compatible avec Ice).",
"Dock": "Dock",
})
FR.update({
"This app refuses to run once it's modified (it checks its own signature). Stack put it back as it was: it has to stay in the Dock.": "Cette app refuse de démarrer une fois modifiée (elle vérifie sa propre signature). Stack l'a remise comme avant : elle doit rester dans le Dock.",
})
FR.update({
"Nothing to do: your apps are already menu bar apps, or have to stay in the Dock.": "Rien à faire : tes apps sont déjà des apps de la barre des menus, ou doivent rester dans le Dock.",
})
FR.update({
"Keep open": "Garder ouverte",
"Keep open: if this app closes, Stack reopens it (unless you quit it from Stack).": "Garder ouverte : si cette app se ferme, Stack la rouvre (sauf si tu la quittes depuis Stack).",
"Out of Dock: no icon at the bottom, the app stays reachable from the menu bar.": "Hors du Dock : pas d'icône en bas, l'app reste accessible en haut dans la barre des menus.",
})
FR.update({
"In Stack": "Dans Stack",
"In Stack: the app leaves Applications and lives inside Stack. Turn off to put it back.": "Dans Stack : l'app quitte Applications et vit dans Stack. Désactive pour la remettre.",
"Lives in Stack": "Rangée dans Stack",
"Inside Stack": "Dans Stack",
"Keep apps inside Stack": "Ranger des apps dans Stack",
"Turn on “In Stack” next to an app: it leaves Applications and Launchpad, and Stack opens it for you.": "Active « Dans Stack » à côté d'une app : elle quitte Applications et le Launchpad, et c'est Stack qui l'ouvre.",
"Apps living in Stack: %lld. They are gone from Applications and Launchpad, and Stack opens them for you.": "Apps rangées dans Stack : %lld. Elles ont quitté Applications et le Launchpad, et c'est Stack qui les ouvre.",
"Show the folder": "Afficher le dossier",
"Put all back in Applications": "Tout remettre dans Applications",
"If you ever delete Stack, put your apps back in Applications first.": "Si un jour tu supprimes Stack, remets d'abord tes apps dans Applications.",
"Keep %@ inside Stack?": "Ranger %@ dans Stack ?",
"Stack moves the real app into its own folder: it disappears from Applications, Launchpad and Spotlight, and you open it from Stack. Nothing inside the app is changed and it keeps its settings. If it's open, it quits and reopens. macOS may ask for your password. Updates from the App Store may no longer find it, and its own “open at login” may stop working (put it in an “open on click” group instead). You can put it back in Applications at any time.": "Stack déplace la vraie app dans son propre dossier : elle disparaît d'Applications, du Launchpad et de Spotlight, et tu l'ouvres depuis Stack. Rien n'est modifié dans l'app et elle garde ses réglages. Si elle est ouverte, elle se ferme puis se rouvre. macOS peut te demander ton mot de passe. Les mises à jour de l'App Store risquent de ne plus la trouver, et son propre « ouvrir au démarrage » peut cesser de marcher (mets-la plutôt dans un groupe « Ouvrir au clic »). Tu peux la remettre dans Applications à tout moment.",
"Move into Stack": "Ranger dans Stack",
"Couldn't move %@": "Impossible de déplacer %@",
"The app is still in Stack's folder.": "L'app est toujours dans le dossier de Stack.",
"This is a system app: macOS doesn't let anyone move it.": "C'est une app système : macOS ne laisse personne la déplacer.",
"There is already an app with this name in this folder:": "Il y a déjà une app avec ce nom dans ce dossier :",
"The app couldn't be moved, so nothing was changed.": "Impossible de déplacer l'app : rien n'a été modifié.",
})
